// Generated by gencpp from file imu_visual/Num.msg
// DO NOT EDIT!


#ifndef IMU_VISUAL_MESSAGE_NUM_H
#define IMU_VISUAL_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_visual
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : first_name()  {
    }
  Num_(const ContainerAllocator& _alloc)
    : first_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _first_name_type;
  _first_name_type first_name;





  typedef boost::shared_ptr< ::imu_visual::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_visual::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::imu_visual::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::imu_visual::Num > NumPtr;
typedef boost::shared_ptr< ::imu_visual::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_visual::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_visual::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace imu_visual

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'imu_visual': ['/home/abdo/captstone/capstone_rosws/src/imu_visual/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::imu_visual::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_visual::Num_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_visual::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_visual::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_visual::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_visual::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_visual::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "80e8c9c65232d3c1560d7601e9eb9de8";
  }

  static const char* value(const ::imu_visual::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x80e8c9c65232d3c1ULL;
  static const uint64_t static_value2 = 0x560d7601e9eb9de8ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_visual::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_visual/Num";
  }

  static const char* value(const ::imu_visual::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_visual::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string first_name\n\
";
  }

  static const char* value(const ::imu_visual::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_visual::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.first_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_visual::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_visual::Num_<ContainerAllocator>& v)
  {
    s << indent << "first_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.first_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_VISUAL_MESSAGE_NUM_H
